env:
        global:
                 - CC_TEST_REPORTER_ID=c1acb763c93f80736cdc3cab0e8a6b30fec1821cdeeff202bde07fe338e9b8c2
language: ruby
rvm:
  - 2.3.8
  - 2.6.2
  - 2.6.3
before_install:
  - gem update --system
  - gem install bundler
before_script:
          - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

